site_name: stojanovic.top
site_url: https://stojanovic.top
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.footer
  palette:
    # Primary theme (default: light)
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Light
    # Dark theme
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Dark
    # Optional: Auto-detect system preference
    #- scheme: preference
    #  toggle:
    #    icon: material/theme-light-dark
    #    name: Auto
